// @ts-check

import { defineConfig } from '@cspell/cspell-types'

const cspellConfig = defineConfig({
  version: '0.2',
  words: [
    'activedescendant',
    'apos',
    'autofix',
    'backreference',
    'camelcase',
    'csrf',
    'gridcell',
    'hashbang',
    'iife',
    'invertable',
    'isnan',
    'ldquo',
    'linebreak',
    'listbox',
    'lsquo',
    'luxon',
    'mischeck',
    'multilines',
    'mysticatea',
    'noassert',
    'nocheck',
    'nonblock',
    'nonconstructor',
    'nonoctal',
    'nonwords',
    'optionless',
    'plusplus',
    'proptypes',
    'radash',
    'radiogroup',
    'rdquo',
    'regexes',
    'rsquo',
    'searchbox',
    'setstate',
    'sonarjs',
    'spinbutton',
    'tablist',
    'tabpanel',
    'textbox',
    'textnodes',
    'treegrid',
    'treeitem',
    'typedefs',
    'yoda',
  ],
})

export default cspellConfig
