// @ts-check

import { defineConfig } from '@cspell/cspell-types'

const cspellConfig = defineConfig({
  version: '0.2',
  language: 'en-US',
  enableGlobDot: true,
  useGitignore: true,
  // `artifacts` holds generated rule schemas, `.gitignore` is upstream boilerplate
  ignorePaths: ['artifacts/**', '.git/**', '.gitignore'],
  words: [
    'activedescendant',
    'apos',
    'chunkname',
    'definitelytyped',
    'elindorath',
    'esmodule',
    'flowtype',
    'gypfile',
    'httponly',
    'innerhtml',
    'invertable',
    'isnan',
    'kramed',
    'ldquo',
    'libc',
    'libxmljs',
    'lingui',
    'lsquo',
    'luxon',
    'mischeck',
    'misrefactored',
    'multilines',
    'mysticatea',
    'networkidle',
    'noassert',
    'nonblock',
    'nonconstructor',
    'nonoctal',
    'nonwords',
    'opensearchservice',
    'optionless',
    'proptypes',
    'radash',
    'rdquo',
    'rsquo',
    'rushstack',
    'scanjs',
    'setstate',
    'sidvind',
    'spinbutton',
    'staycation',
    'tablist',
    'textnodes',
    'thenables',
    'toplevel',
    'touchables',
    'treegrid',
    'unsanitized',
    'unthrown',
  ],
})

export default cspellConfig
