'use strict';


const OFF = 'off';
const WARN = 'warn';
const ERROR = 'error';


module.exports = {
  rules: {
    // OFF as we already enforce parens around arrow function arguments
    // with the core rule arrow-parens
    '@elindorath/mysticatea/arrow-parens': [OFF],
    // OFF as we enforce to not use var
    '@elindorath/mysticatea/block-scoped-var': [OFF],
    // OFF as it is duplicate of the rule unicorn/no-array-instanceof
    '@elindorath/mysticatea/no-instanceof-array': [OFF],
    '@elindorath/mysticatea/no-instanceof-wrapper': [ERROR],
    '@elindorath/mysticatea/no-literal-call': [ERROR],
    '@elindorath/mysticatea/no-this-in-static': [ERROR],
    // OFF as we don't ignore var in the core rule no-unused-var
    '@elindorath/mysticatea/no-use-ignored-vars': [OFF],
    // Don't know who will do what is catched by this rule
    '@elindorath/mysticatea/no-useless-rest-spread': [ERROR],
    // Might conflict with the rule unicorn/no-for-loop
    '@elindorath/mysticatea/prefer-for-of': [ERROR],

    /* ----- Foreign rules ----- */
    // Disable all foreign rules as it would be duplicate
    '@elindorath/mysticatea/eslint-comments/disable-enable-pair': [OFF],
    '@elindorath/mysticatea/eslint-comments/no-aggregating-enable': [OFF],
    '@elindorath/mysticatea/eslint-comments/no-duplicate-disable': [OFF],
    '@elindorath/mysticatea/eslint-comments/no-restricted-disable': [OFF],
    '@elindorath/mysticatea/eslint-comments/no-unlimited-disable': [OFF],
    '@elindorath/mysticatea/eslint-comments/no-unused-disable': [OFF],
    '@elindorath/mysticatea/eslint-comments/no-unused-enable': [OFF],
    '@elindorath/mysticatea/eslint-comments/no-use': [OFF],
    '@elindorath/mysticatea/eslint-plugin/consistent-output': [OFF],
    '@elindorath/mysticatea/eslint-plugin/fixer-return': [OFF],
    '@elindorath/mysticatea/eslint-plugin/meta-property-ordering': [OFF],
    '@elindorath/mysticatea/eslint-plugin/no-deprecated-context-methods': [OFF],
    '@elindorath/mysticatea/eslint-plugin/no-deprecated-report-api': [OFF],
    '@elindorath/mysticatea/eslint-plugin/no-identical-tests': [OFF],
    '@elindorath/mysticatea/eslint-plugin/no-missing-placeholders': [OFF],
    '@elindorath/mysticatea/eslint-plugin/no-unused-placeholders': [OFF],
    '@elindorath/mysticatea/eslint-plugin/no-useless-token-range': [OFF],
    '@elindorath/mysticatea/eslint-plugin/prefer-output-null': [OFF],
    '@elindorath/mysticatea/eslint-plugin/prefer-placeholders': [OFF],
    '@elindorath/mysticatea/eslint-plugin/prefer-replace-text': [OFF],
    '@elindorath/mysticatea/eslint-plugin/report-message-format': [OFF],
    '@elindorath/mysticatea/eslint-plugin/require-meta-docs-url': [OFF],
    '@elindorath/mysticatea/eslint-plugin/require-meta-fixable': [OFF],
    '@elindorath/mysticatea/eslint-plugin/require-meta-type': [OFF],
    '@elindorath/mysticatea/eslint-plugin/test-case-property-ordering': [OFF],
    '@elindorath/mysticatea/eslint-plugin/test-case-shorthand-strings': [OFF],
    '@elindorath/mysticatea/node/exports-style': [OFF],
    '@elindorath/mysticatea/node/file-extension-in-import': [OFF],
    '@elindorath/mysticatea/node/no-callback-literal': [OFF],
    '@elindorath/mysticatea/node/no-deprecated-api': [OFF],
    '@elindorath/mysticatea/node/no-exports-assign': [OFF],
    '@elindorath/mysticatea/node/no-extraneous-import': [OFF],
    '@elindorath/mysticatea/node/no-extraneous-require': [OFF],
    '@elindorath/mysticatea/node/no-missing-import': [OFF],
    '@elindorath/mysticatea/node/no-missing-require': [OFF],
    '@elindorath/mysticatea/node/no-unpublished-bin': [OFF],
    '@elindorath/mysticatea/node/no-unpublished-import': [OFF],
    '@elindorath/mysticatea/node/no-unpublished-require': [OFF],
    '@elindorath/mysticatea/node/no-unsupported-features/es-builtins': [OFF],
    '@elindorath/mysticatea/node/no-unsupported-features/es-syntax': [OFF],
    '@elindorath/mysticatea/node/no-unsupported-features/node-builtins': [OFF],
    '@elindorath/mysticatea/node/prefer-global/buffer': [OFF],
    '@elindorath/mysticatea/node/prefer-global/console': [OFF],
    '@elindorath/mysticatea/node/prefer-global/process': [OFF],
    '@elindorath/mysticatea/node/prefer-global/text-decoder': [OFF],
    '@elindorath/mysticatea/node/prefer-global/text-encoder': [OFF],
    '@elindorath/mysticatea/node/prefer-global/url': [OFF],
    '@elindorath/mysticatea/node/prefer-global/url-search-params': [OFF],
    '@elindorath/mysticatea/node/prefer-promises/dns': [OFF],
    '@elindorath/mysticatea/node/prefer-promises/fs': [OFF],
    '@elindorath/mysticatea/node/process-exit-as-throw': [OFF],
    '@elindorath/mysticatea/node/shebang': [OFF],
    '@elindorath/mysticatea/prettier': [OFF],
    '@elindorath/mysticatea/vue/array-bracket-spacing': [OFF],
    '@elindorath/mysticatea/vue/arrow-spacing': [OFF],
    '@elindorath/mysticatea/vue/attribute-hyphenation': [OFF],
    '@elindorath/mysticatea/vue/attributes-order': [OFF],
    '@elindorath/mysticatea/vue/block-spacing': [OFF],
    '@elindorath/mysticatea/vue/brace-style': [OFF],
    '@elindorath/mysticatea/vue/camelcase': [OFF],
    '@elindorath/mysticatea/vue/comma-dangle': [OFF],
    '@elindorath/mysticatea/vue/comment-directive': [OFF],
    '@elindorath/mysticatea/vue/component-name-in-template-casing': [OFF],
    '@elindorath/mysticatea/vue/dot-location': [OFF],
    '@elindorath/mysticatea/vue/eqeqeq': [OFF],
    '@elindorath/mysticatea/vue/html-closing-bracket-newline': [OFF],
    '@elindorath/mysticatea/vue/html-closing-bracket-spacing': [OFF],
    '@elindorath/mysticatea/vue/html-end-tags': [OFF],
    '@elindorath/mysticatea/vue/html-indent': [OFF],
    '@elindorath/mysticatea/vue/html-quotes': [OFF],
    '@elindorath/mysticatea/vue/html-self-closing': [OFF],
    '@elindorath/mysticatea/vue/jsx-uses-vars': [OFF],
    '@elindorath/mysticatea/vue/key-spacing': [OFF],
    '@elindorath/mysticatea/vue/keyword-spacing': [OFF],
    '@elindorath/mysticatea/vue/match-component-file-name': [OFF],
    '@elindorath/mysticatea/vue/max-attributes-per-line': [OFF],
    '@elindorath/mysticatea/vue/multiline-html-element-content-newline': [OFF],
    '@elindorath/mysticatea/vue/mustache-interpolation-spacing': [OFF],
    '@elindorath/mysticatea/vue/name-property-casing': [OFF],
    '@elindorath/mysticatea/vue/no-async-in-computed-properties': [OFF],
    '@elindorath/mysticatea/vue/no-boolean-default': [OFF],
    '@elindorath/mysticatea/vue/no-deprecated-scope-attribute': [OFF],
    '@elindorath/mysticatea/vue/no-dupe-keys': [OFF],
    '@elindorath/mysticatea/vue/no-duplicate-attributes': [OFF],
    '@elindorath/mysticatea/vue/no-empty-pattern': [OFF],
    '@elindorath/mysticatea/vue/no-multi-spaces': [OFF],
    '@elindorath/mysticatea/vue/no-parsing-error': [OFF],
    '@elindorath/mysticatea/vue/no-reserved-keys': [OFF],
    '@elindorath/mysticatea/vue/no-restricted-syntax': [OFF],
    '@elindorath/mysticatea/vue/no-shared-component-data': [OFF],
    '@elindorath/mysticatea/vue/no-side-effects-in-computed-properties': [OFF],
    '@elindorath/mysticatea/vue/no-spaces-around-equal-signs-in-attribute': [OFF],
    '@elindorath/mysticatea/vue/no-template-key': [OFF],
    '@elindorath/mysticatea/vue/no-template-shadow': [OFF],
    '@elindorath/mysticatea/vue/no-textarea-mustache': [OFF],
    '@elindorath/mysticatea/vue/no-unused-components': [OFF],
    '@elindorath/mysticatea/vue/no-unused-vars': [OFF],
    '@elindorath/mysticatea/vue/no-use-v-if-with-v-for': [OFF],
    '@elindorath/mysticatea/vue/no-v-html': [OFF],
    '@elindorath/mysticatea/vue/object-curly-spacing': [OFF],
    '@elindorath/mysticatea/vue/order-in-components': [OFF],
    '@elindorath/mysticatea/vue/prop-name-casing': [OFF],
    '@elindorath/mysticatea/vue/require-component-is': [OFF],
    '@elindorath/mysticatea/vue/require-default-prop': [OFF],
    '@elindorath/mysticatea/vue/require-direct-export': [OFF],
    '@elindorath/mysticatea/vue/require-prop-type-constructor': [OFF],
    '@elindorath/mysticatea/vue/require-prop-types': [OFF],
    '@elindorath/mysticatea/vue/require-render-return': [OFF],
    '@elindorath/mysticatea/vue/require-v-for-key': [OFF],
    '@elindorath/mysticatea/vue/require-valid-default-prop': [OFF],
    '@elindorath/mysticatea/vue/return-in-computed-property': [OFF],
    '@elindorath/mysticatea/vue/script-indent': [OFF],
    '@elindorath/mysticatea/vue/singleline-html-element-content-newline': [OFF],
    '@elindorath/mysticatea/vue/space-infix-ops': [OFF],
    '@elindorath/mysticatea/vue/space-unary-ops': [OFF],
    '@elindorath/mysticatea/vue/this-in-template': [OFF],
    '@elindorath/mysticatea/vue/use-v-on-exact': [OFF],
    '@elindorath/mysticatea/vue/v-bind-style': [OFF],
    '@elindorath/mysticatea/vue/v-on-function-call': [OFF],
    '@elindorath/mysticatea/vue/v-on-style': [OFF],
    '@elindorath/mysticatea/vue/v-slot-style': [OFF],
    '@elindorath/mysticatea/vue/valid-template-root': [OFF],
    '@elindorath/mysticatea/vue/valid-v-bind': [OFF],
    '@elindorath/mysticatea/vue/valid-v-cloak': [OFF],
    '@elindorath/mysticatea/vue/valid-v-else': [OFF],
    '@elindorath/mysticatea/vue/valid-v-else-if': [OFF],
    '@elindorath/mysticatea/vue/valid-v-for': [OFF],
    '@elindorath/mysticatea/vue/valid-v-html': [OFF],
    '@elindorath/mysticatea/vue/valid-v-if': [OFF],
    '@elindorath/mysticatea/vue/valid-v-model': [OFF],
    '@elindorath/mysticatea/vue/valid-v-on': [OFF],
    '@elindorath/mysticatea/vue/valid-v-once': [OFF],
    '@elindorath/mysticatea/vue/valid-v-pre': [OFF],
    '@elindorath/mysticatea/vue/valid-v-show': [OFF],
    '@elindorath/mysticatea/vue/valid-v-slot': [OFF],
    '@elindorath/mysticatea/vue/valid-v-text': [OFF],
  },
};
