/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY 'scripts/generate-foreign.js'.
 */

'use strict';

const { processors } = require('eslint-plugin-optimize-regex');


module.exports = Object.entries(processors || {}).reduce((object, [processorId, processorDefinition]) => ({
  ...object,
  [`optimize-regex/${processorId}`]: processorDefinition,
}), {});
