/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY 'scripts/generate-foreign.js'.
 */

'use strict';

const { processors } = require('eslint-plugin-react-redux');


module.exports = Object.entries(processors || {}).reduce((prefixedProcessors, [processorId, processorDefinition]) => ({
  ...prefixedProcessors,
  [`react-redux/${processorId}`]: processorDefinition,
}), {});
