/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY 'scripts/generate-foreign.js'.
 */

'use strict';

const { processors } = require('@shopify/eslint-plugin');


module.exports = Object.entries(processors || {}).reduce((object, [processorId, processorDefinition]) => ({
  ...object,
  [`shopify/${processorId}`]: processorDefinition,
}), {});
