/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY 'scripts/generate-config.js'.
 */

'use strict';

module.exports = {
  '+babel': require('./configs/+babel'),
  '+browser': require('./configs/+browser'),
  '+dev': require('./configs/+dev'),
  '+jest': require('./configs/+jest'),
  '+json': require('./configs/+json'),
  '+jsx': require('./configs/+jsx'),
  '+module-type': require('./configs/+module-type'),
  '+node': require('./configs/+node'),
  '+react-native': require('./configs/+react-native'),
  '+react-only': require('./configs/+react-only'),
  '+react': require('./configs/+react'),
  '+script-type': require('./configs/+script-type'),
  common: require('./configs/common'),
  'project-eslint-plugin': require('./configs/project-eslint-plugin'),
  'project-react-native': require('./configs/project-react-native'),
};
