#! /usr/bin/env -S yarn tsx

import path from 'node:path'
import process from 'node:process'

import fs from 'fs-extra'
import { readPackageUp } from 'read-package-up'


try {
  const { name, packageDirectoryPath, version } = await readMeta()
  const fileContent = `\
/**
 * DO NOT EDIT THIS FILE WHICH WAS GENERATED BY '${path.relative(packageDirectoryPath, import.meta.filename)}'.
 */

export const meta = {
  name: '${name}',
  version: '${version}',
}
`

  await fs.outputFile(path.resolve(packageDirectoryPath, 'src/meta.ts'), fileContent)
} catch (error) {
  console.error(error)
  process.exitCode = 1
}

async function readMeta() {
  const result = await readPackageUp({ cwd: import.meta.dirname, normalize: true })

  if (!result) {
    throw new Error('No relative package.json found')
  }

  return {
    name: result.packageJson.name,
    packageDirectoryPath: path.dirname(result.path),
    version: result.packageJson.version,
  }
}
