#! /usr/bin/env node

'use strict';

const path = require('path');
const process = require('process');

const fs = require('fs-extra');
const { ESLint } = require('eslint');


/* eslint-disable @elindorath/promise/prefer-await-to-callbacks -- Required for entrypoint in node context */
(async function main() {
  const { readPackageUp } = await import('read-pkg-up');

  const eslint = new ESLint({ fix: true });
  const { packageJson: { dependencies } } = await readPackageUp();

  for await (const [packageName] of Object.entries(dependencies)) {
    if (isEslintPlugin(packageName)) {
      await generateExportingPlugin(packageName, 'environment', eslint);
      await generateExportingPlugin(packageName, 'processor', eslint);
      await generateExportingPlugin(packageName, 'rule', eslint);
    }
  }
})().catch((error) => {
  process.exitCode = 1;
  console.error(error);
});
/* eslint-enable */


function isEslintPlugin(packageName) {
  return packageName.includes('eslint-plugin');
}

async function generateExportingPlugin(packageName, type, eslint) {
  const { packageDirectorySync } = await import('pkg-dir');

  const eslintPluginName = getEslintPluginName(packageName);
  const targetFile = path.resolve(__dirname, `../lib/foreign-${type}s`, `${eslintPluginName}.js`);
  const capitalizedType = `${type[0].toUpperCase()}${type.slice(1)}`;

  await fs.outputFile(
    targetFile,
    `\
/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY '${path.relative(packageDirectorySync(__dirname), __filename)}'.
 */

'use strict';

const { ${type}s } = require('${packageName}');


module.exports = Object.entries(${type}s || {}).reduce((prefixed${capitalizedType}s, [${type}Id, ${type}Definition]) => {
  return {
    ...prefixed${capitalizedType}s,
    [\`${eslintPluginName}/\${${type}Id}\`]: ${type}Definition,
  };
}, {});
`
  );

  try {
    const result = await eslint.lintFiles([targetFile]);

    await ESLint.outputFixes(result);
  } catch (error) {
    console.log(error.message);
    console.log('Failed to fix lint error, try to run it again');
  }
}

function getEslintPluginName(packageName) {
  const [firstLetter] = packageName;

  return firstLetter === '@'
    ? packageName.slice(firstLetter.length, packageName.indexOf('/'))
    : packageName.slice('eslint-plugin-'.length);
}
