'use strict'

const path = require('node:path')
const process = require('node:process')

const { ESLint } = require('eslint')
const fs = require('fs-extra')
const packageDirectory = require('pkg-dir');


(async function main() {
  const targetFile = path.resolve(__dirname, `../lib/configs.js`)
  const configFileNames = await fs.readdir(path.resolve(__dirname, `../lib/configs`))

  await fs.outputFile(
    targetFile,
    `\
/**
* DON'T EDIT THIS FILE WHICH WAS GENERATED BY '${path.relative(packageDirectory.sync(__dirname), __filename)}'.
*/

'use strict';

module.exports = {
${configFileNames
    .map((fileName) => path.basename(fileName, '.js'))
    .filter((id) => !id.startsWith('_') && id !== 'plugins')
    .map((id) => `  '${id}': require('./configs/${id}'),`)
    .join('\n')}
};
`
  )

  try {
    const eslint = new ESLint({ fix: true })
    const result = await eslint.lintFiles([targetFile])

    await ESLint.outputFixes(result)
  } catch (error) {
    console.log(error.message)
    console.log('Failed to fix lint error, try to run it again')
  }
// eslint-disable-next-line promise/prefer-await-to-callbacks -- require as we can't use global await
})().catch((error) => {
  process.exitCode = 1
  console.error(error)
})
