/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY 'scripts/generate-foreign.js'.
 */

'use strict';

const { environments } = require('@babel/eslint-plugin');


module.exports = Object.entries(environments || {}).reduce((object, [environmentId, environmentDefinition]) => ({
  ...object,
  [`babel/${environmentId}`]: environmentDefinition,
}), {});
