/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY 'scripts/generate-foreign.js'.
 */

'use strict';

const { environments } = require('eslint-plugin-flowtype');


module.exports = Object.entries(environments || {}).reduce((object, [environmentId, environmentDefinition]) => ({
  ...object,
  [`flowtype/${environmentId}`]: environmentDefinition,
}), {});
