/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY 'scripts/generate-foreign.js'.
 */

'use strict';

const { environments } = require('eslint-plugin-jsx-a11y');


module.exports = Object.entries(environments || {}).reduce((object, [environmentId, environmentDefinition]) => ({
  ...object,
  [`jsx-a11y/${environmentId}`]: environmentDefinition,
}), {});
