/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY 'scripts/generate-foreign.js'.
 */

'use strict';

const { environments } = require('@mysticatea/eslint-plugin');


module.exports = Object.entries(environments || {}).reduce((object, [environmentId, environmentDefinition]) => ({
  ...object,
  [`mysticatea/${environmentId}`]: environmentDefinition,
}), {});
