/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY 'scripts/generate-foreign.js'.
 */

'use strict';

const { environments } = require('eslint-plugin-react-native');


module.exports = Object.entries(environments || {}).reduce((prefixedEnvironments, [environmentId, environmentDefinition]) => ({
  ...prefixedEnvironments,
  [`react-native/${environmentId}`]: environmentDefinition,
}), {});
