/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY 'scripts/generate-foreign.js'.
 */

'use strict';

const { rules } = require('eslint-plugin-filenames');


module.exports = Object.entries(rules || {}).reduce((object, [ruleId, ruleDefinition]) => ({
  ...object,
  [`filenames/${ruleId}`]: ruleDefinition,
}), {});
