/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY 'scripts/generate-foreign.js'.
 */

'use strict';

const { rules } = require('eslint-plugin-jsx-a11y');


module.exports = Object.entries(rules || {}).reduce((prefixedRules, [ruleId, ruleDefinition]) => ({
  ...prefixedRules,
  [`jsx-a11y/${ruleId}`]: ruleDefinition,
}), {});
