/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY 'scripts/generate-foreign.js'.
 */

'use strict';

const { rules } = require('@mysticatea/eslint-plugin');


module.exports = Object.entries(rules || {}).reduce((object, [ruleId, ruleDefinition]) => ({
  ...object,
  [`mysticatea/${ruleId}`]: ruleDefinition,
}), {});
