/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY 'scripts/generate-foreign.js'.
 */

'use strict';

const { rules } = require('eslint-plugin-react-i18n');


module.exports = Object.entries(rules || {}).reduce((object, [ruleId, ruleDefinition]) => ({
  ...object,
  [`react-i18n/${ruleId}`]: ruleDefinition,
}), {});
