/**
* DON'T EDIT THIS FILE WHICH WAS GENERATED BY 'scripts/generate-config.js'.
*/
/* eslint-disable import/max-dependencies -- We need to import all of that here */
/* eslint-disable n/global-require -- Respect the format of eslint-plugin */

'use strict';

module.exports = {
  // '+babel': require('./configs/+babel'),
  // '+browser': require('./configs/+browser'),
  // '+cli': require('./configs/+cli'),
  // '+dev': require('./configs/+dev'),
  // '+eslintrc': require('./configs/+eslintrc'),
  // '+jest': require('./configs/+jest'),
  // '+json': require('./configs/+json'),
  // '+jsx': require('./configs/+jsx'),
  // '+module-type': require('./configs/+module-type'),
  // '+node': require('./configs/+node'),
  // '+react-native': require('./configs/+react-native'),
  // '+react-only': require('./configs/+react-only'),
  // '+react': require('./configs/+react'),
  // '+script-type': require('./configs/+script-type'),
  // common: require('./configs/common'),
  // 'project-cli': require('./configs/project-cli'),
  'environment-node-source-type-commonjs': require('./configs/environment-node-source-type-commonjs.js'),
  'environment-node': require('./configs/environment-node.js'),
  'library-jest': require('./configs/library-jest.js'),
  'library-jest&syntax-typescript': require('./configs/library-jest&syntax-typescript.js'),
  'library-react-native&syntax-jsx': require('./configs/library-react-native&syntax-jsx.js'),
  'library-react': require('./configs/library-react.js'),
  'library-react&syntax-jsx': require('./configs/library-react&syntax-jsx.js'),
  'source-type-commonjs': require('./configs/source-type-commonjs.js'),
  'syntax-jsx': require('./configs/syntax-jsx.js'),
  'syntax-typescript': require('./configs/syntax-typescript.js'),
  'vanilla': require('./configs/vanilla.js'),
  'project-eslint-plugin': require('./configs/projects/eslint-plugin.js'),
  'project-react-native': require('./configs/projects/react-native.js'),
  'project-react': require('./configs/projects/react.js'),
};

/* eslint-enable */
