name: CI
run-name: CI
on: [pull_request]
jobs:
  check:
    name: ${{ matrix.check }}
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        check:
          - lint
          - type-check
          - test-build
          - test-update
          - test-reachability
          - test-schema
          - test-scripts
          - spellcheck
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v7

      - name: Enable Corepack
        run: corepack enable

      - name: Setup node
        id: node
        uses: actions/setup-node@v7
        with:
          node-version-file: 'package.json'
          check-latest: false
          cache: 'yarn'

      - name: Install node modules
        id: node-modules
        run: |
          yarn install \
            --immutable

      - name: Run check
        id: check
        run: |
          yarn run ${{ matrix.check }}
